### ISSUE TITLE
Support for longer text

### ISSUE THREAD

**Issue by ShuyangCao** [AIPHES/DiscoScore#4]
Thanks for releasing the code. 

I tried running on longer text (> 512 tokens). It seems the current version only supports text containing <= 512 tokens. Any plan to add support for longer text?

**Comment by andyweizhao** [comment]
Hi, many thanks for your attention! 

You could replace [the code of initializing BERT](https://github.com/AIPHES/DiscoScore/blob/main/disco_score/metrics/metrics.py#L12) with Longformer by the following code! 
```

from transformers import LongformerModel, LongformerTokenizer

model = LongformerModel.from_pretrained('allenai/longformer-base-4096')
tokenizer = LongformerTokenizer.from_pretrained('allenai/longformer-base-4096')
```

**Comment by ShuyangCao** [comment]
I replaced the code here with a sliding window solution.
https://github.com/AIPHES/DiscoScore/blob/4f2c5934eea8f3ea443e4a133d54277d6e32e23a/disco_score/metrics/focus_diff.py#L26-L30

```python
def bert_encode(model, x, attention_mask):
    model.eval()
    with torch.no_grad():
        seq_len = x.size(1)
        seq_len = max(seq_len, 512)
        last_hidden_states = []
        # sliding window for long documents
        for i in range(512, seq_len + 256, 256):
            chunk_select_idx = 0 if i == 512 else 256
            last_hidden_states.append(model(input_ids = x[:, i-512:i], token_type_ids = None, attention_mask = attention_mask[:, i-512:i]).last_hidden_state[:, chunk_select_idx:, :])
        output = torch.cat(last_hidden_states, dim=1)
        
        return output
```

I guess either using Longformer or doing sliding window can work, but not sure which performs better.

**Comment by andyweizhao** [comment]
Indeed, the roots of Longformer are from sliding window, i.e., convolution - it overlaps tokens across windows to some degree. Not sure if this has been supported in your implementation.
